name = "creator-field-assistant-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "creator-field-assistant"
database_id = "13bffbe4-b74e-44bf-8443-90893d4e85a5"

[[kv_namespaces]]
binding = "KV"
id = "064c80511aae4d088944279b105ff93c"
